source 'https://rubygems.org'

# Specify your gem's dependencies in zss.gemspec
gem 'bundler'
gem 'rake'
gem 'rspec'
gem 'pry'
gem 'simplecov'
gem 'codeclimate-test-reporter'
gem 'bump'
gem 'activerecord'
gem 'hashie'
gem 'activesupport'
gem 'zss', , git: 'git@github.com:jrmossad/zmq-service-suite-ruby.git'
gem 'redis-namespace'