source 'https://rubygems.org'

# Specify your gem's dependencies in zss.gemspec
gem 'bundler'
gem 'rake', '~> 10.3'
gem 'rspec', '~> 3.0'
gem 'pry', '~> 0.10'
gem 'simplecov', '~> 0.9'
gem 'codeclimate-test-reporter', '~> 0.3'
gem 'bump', '~> 0.5'
gem 'activerecord', '~> 4.2.1'
gem 'hashie', '~> 3.2'
gem 'activesupport', '~> 4.2'
gem 'zss', , git: 'git@github.com:jrmossad/zmq-service-suite-ruby.git'
gem 'redis-namespace'
